// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("venafi");
/**
 * Access token for CyberArk Certificate Manager, Self-Hosted, user should use this for authentication
 * 
 */
    public Optional<String> accessToken() {
        return Codegen.stringProp("accessToken").config(config).get();
    }
/**
 * API key for CyberArk Certificate Manager, SaaS. Example: 142231b7-cvb0-412e-886b-6aeght0bc93d
 * 
 */
    public Optional<String> apiKey() {
        return Codegen.stringProp("apiKey").config(config).get();
    }
/**
 * application that will be using the token
 * 
 */
    public Optional<String> clientId() {
        return Codegen.stringProp("clientId").config(config).get();
    }
/**
 * Client Secret for CyberArk Certificate Manager, Self-Hosted or Palo Alto Networks Next-Gen Trust Security (NGTS)
 * 
 */
    public Optional<String> clientSecret() {
        return Codegen.stringProp("clientSecret").config(config).get();
    }
/**
 * When set to true, the resulting certificate will be issued by an ephemeral, no trust CA rather than enrolling using CyberArk Certificate Manager, SaaS or CyberArk Certificate Manager, Self-Hosted. Useful for development and testing
 * 
 */
    public Optional<Boolean> devMode() {
        return Codegen.booleanProp("devMode").config(config).get();
    }
/**
 * JWT of the identity provider associated to the CyberArk Certificate Manager, SaaS service account that is granting the access token
 * 
 */
    public Optional<String> externalJwt() {
        return Codegen.stringProp("externalJwt").config(config).get();
    }
/**
 * Base64 encoded PKCS#12 keystore containing a client certificate, private key, and chain certificates to authenticate to CyberArk Certificate Manager, Self-Hosted
 * 
 */
    public Optional<String> p12CertData() {
        return Codegen.stringProp("p12CertData").config(config).get();
    }
/**
 * Filename of PKCS#12 keystore containing a client certificate, private key, and chain certificates to authenticate to CyberArk Certificate Manager, Self-Hosted
 * 
 */
    public Optional<String> p12CertFilename() {
        return Codegen.stringProp("p12CertFilename").config(config).get();
    }
/**
 * Password for the PKCS#12 keystore declared in p12Cert / p12_cert_data
 * 
 */
    public Optional<String> p12CertPassword() {
        return Codegen.stringProp("p12CertPassword").config(config).get();
    }
/**
 * When true, certificates will not be retired on CyberArk platforms when terraform destroy is run. Default is false
 * 
 */
    public Optional<Boolean> skipRetirement() {
        return Codegen.booleanProp("skipRetirement").config(config).get();
    }
/**
 * Endpoint URL to request new CyberArk Certificate Manager, SaaS access tokens
 * 
 */
    public Optional<String> tokenUrl() {
        return Codegen.stringProp("tokenUrl").config(config).get();
    }
/**
 * Password for WebSDK user. Example: password
 * 
 */
    public Optional<String> tppPassword() {
        return Codegen.stringProp("tppPassword").config(config).get();
    }
/**
 * WebSDK user for CyberArk Certificate Manager, Self-Hosted. Example: admin
 * 
 */
    public Optional<String> tppUsername() {
        return Codegen.stringProp("tppUsername").config(config).get();
    }
/**
 * Use to specify a PEM-formatted file that contains certificates to be trust anchors for all communications with the CyberArk Web Service.
 * Example:
 *   trustBundle = &#34;${file(&#34;chain.pem&#34;)}&#34;
 * 
 */
    public Optional<String> trustBundle() {
        return Codegen.stringProp("trustBundle").config(config).get();
    }
/**
 * The Palo Alto Networks Next-Gen Trust Security (NGTS) TSG ID to use when issuing a token. Only used if platform is detected as &#39;ngts&#39;
 * 
 */
    public Optional<String> tsgId() {
        return Codegen.stringProp("tsgId").config(config).get();
    }
/**
 * The CyberArk Platform URL. Example: https://cmsh.cyberark.example/vedsdk
 * 
 */
    public Optional<String> url() {
        return Codegen.stringProp("url").config(config).get();
    }
/**
 * DN of the CyberArk Certificate Manager, Self-Hosted policy folder or name of the CyberArk Certificate Manager, SaaS application plus issuing template alias.
 * Example for CyberArk Certificate Manager, Self-Hosted: testPolicy\\vault
 * Example for CyberArk Certificate Manager, SaaS: myApp\\Default
 * 
 */
    public Optional<String> zone() {
        return Codegen.stringProp("zone").config(config).get();
    }
}
