// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class SshConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final SshConfigArgs Empty = new SshConfigArgs();

    /**
     * The SSH certificate issuing template.
     * 
     */
    @Import(name="template", required=true)
    private Output<String> template;

    /**
     * @return The SSH certificate issuing template.
     * 
     */
    public Output<String> template() {
        return this.template;
    }

    private SshConfigArgs() {}

    private SshConfigArgs(SshConfigArgs $) {
        this.template = $.template;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SshConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SshConfigArgs $;

        public Builder() {
            $ = new SshConfigArgs();
        }

        public Builder(SshConfigArgs defaults) {
            $ = new SshConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param template The SSH certificate issuing template.
         * 
         * @return builder
         * 
         */
        public Builder template(Output<String> template) {
            $.template = template;
            return this;
        }

        /**
         * @param template The SSH certificate issuing template.
         * 
         * @return builder
         * 
         */
        public Builder template(String template) {
            return template(Output.of(template));
        }

        public SshConfigArgs build() {
            if ($.template == null) {
                throw new MissingRequiredPropertyException("SshConfigArgs", "template");
            }
            return $;
        }
    }

}
