// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package venafi

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-venafi/sdk/go/venafi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "venafi:index/certificate:Certificate":
		r = &Certificate{}
	case "venafi:index/cloudKeystoreInstallation:CloudKeystoreInstallation":
		r = &CloudKeystoreInstallation{}
	case "venafi:index/policy:Policy":
		r = &Policy{}
	case "venafi:index/sshCertificate:SshCertificate":
		r = &SshCertificate{}
	case "venafi:index/sshConfig:SshConfig":
		r = &SshConfig{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:venafi" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"venafi",
		"index/certificate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"venafi",
		"index/cloudKeystoreInstallation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"venafi",
		"index/policy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"venafi",
		"index/sshCertificate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"venafi",
		"index/sshConfig",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"venafi",
		&pkg{version},
	)
}
