// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CloudKeystoreInstallationState extends com.pulumi.resources.ResourceArgs {

    public static final CloudKeystoreInstallationState Empty = new CloudKeystoreInstallationState();

    /**
     * ARN of the AWS certificate. Use it to provision the VCP certificate to an existing ACM certificate, instead of a new one. Only valid for ACM keystores.
     * 
     */
    @Import(name="arn")
    private @Nullable Output<String> arn;

    /**
     * @return ARN of the AWS certificate. Use it to provision the VCP certificate to an existing ACM certificate, instead of a new one. Only valid for ACM keystores.
     * 
     */
    public Optional<Output<String>> arn() {
        return Optional.ofNullable(this.arn);
    }

    /**
     * ID of the certificate to be provisioned to the given `keystore_id`.
     * 
     */
    @Import(name="certificateId")
    private @Nullable Output<String> certificateId;

    /**
     * @return ID of the certificate to be provisioned to the given `keystore_id`.
     * 
     */
    public Optional<Output<String>> certificateId() {
        return Optional.ofNullable(this.certificateId);
    }

    /**
     * The ID of the provisioned certificate within the Cloud Keystore
     * 
     */
    @Import(name="cloudCertificateId")
    private @Nullable Output<String> cloudCertificateId;

    /**
     * @return The ID of the provisioned certificate within the Cloud Keystore
     * 
     */
    public Optional<Output<String>> cloudCertificateId() {
        return Optional.ofNullable(this.cloudCertificateId);
    }

    /**
     * Metadata of the provisioned certificate from the Cloud Keystore
     * 
     */
    @Import(name="cloudCertificateMetadata")
    private @Nullable Output<Map<String,String>> cloudCertificateMetadata;

    /**
     * @return Metadata of the provisioned certificate from the Cloud Keystore
     * 
     */
    public Optional<Output<Map<String,String>>> cloudCertificateMetadata() {
        return Optional.ofNullable(this.cloudCertificateMetadata);
    }

    /**
     * Name for the provisioned certificate in the keystore. If the name already exists, the provisioning will replace the previous certificate with the one from `certificate_id`. Only valid for AKV and GCM keystores.
     * 
     */
    @Import(name="cloudCertificateName")
    private @Nullable Output<String> cloudCertificateName;

    /**
     * @return Name for the provisioned certificate in the keystore. If the name already exists, the provisioning will replace the previous certificate with the one from `certificate_id`. Only valid for AKV and GCM keystores.
     * 
     */
    public Optional<Output<String>> cloudCertificateName() {
        return Optional.ofNullable(this.cloudCertificateName);
    }

    /**
     * ID of the cloud keystore where the certificate will be provisioned.
     * 
     */
    @Import(name="cloudKeystoreId")
    private @Nullable Output<String> cloudKeystoreId;

    /**
     * @return ID of the cloud keystore where the certificate will be provisioned.
     * 
     */
    public Optional<Output<String>> cloudKeystoreId() {
        return Optional.ofNullable(this.cloudKeystoreId);
    }

    /**
     * The GCM certificate scope of the certificate. Only valid for GCM keystores. Supported values from GCM API documentation: DEFAULT, EDGE_CACHE, ALL_REGIONS.
     * 
     */
    @Import(name="gcmCertScope")
    private @Nullable Output<String> gcmCertScope;

    /**
     * @return The GCM certificate scope of the certificate. Only valid for GCM keystores. Supported values from GCM API documentation: DEFAULT, EDGE_CACHE, ALL_REGIONS.
     * 
     */
    public Optional<Output<String>> gcmCertScope() {
        return Optional.ofNullable(this.gcmCertScope);
    }

    private CloudKeystoreInstallationState() {}

    private CloudKeystoreInstallationState(CloudKeystoreInstallationState $) {
        this.arn = $.arn;
        this.certificateId = $.certificateId;
        this.cloudCertificateId = $.cloudCertificateId;
        this.cloudCertificateMetadata = $.cloudCertificateMetadata;
        this.cloudCertificateName = $.cloudCertificateName;
        this.cloudKeystoreId = $.cloudKeystoreId;
        this.gcmCertScope = $.gcmCertScope;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CloudKeystoreInstallationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CloudKeystoreInstallationState $;

        public Builder() {
            $ = new CloudKeystoreInstallationState();
        }

        public Builder(CloudKeystoreInstallationState defaults) {
            $ = new CloudKeystoreInstallationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param arn ARN of the AWS certificate. Use it to provision the VCP certificate to an existing ACM certificate, instead of a new one. Only valid for ACM keystores.
         * 
         * @return builder
         * 
         */
        public Builder arn(@Nullable Output<String> arn) {
            $.arn = arn;
            return this;
        }

        /**
         * @param arn ARN of the AWS certificate. Use it to provision the VCP certificate to an existing ACM certificate, instead of a new one. Only valid for ACM keystores.
         * 
         * @return builder
         * 
         */
        public Builder arn(String arn) {
            return arn(Output.of(arn));
        }

        /**
         * @param certificateId ID of the certificate to be provisioned to the given `keystore_id`.
         * 
         * @return builder
         * 
         */
        public Builder certificateId(@Nullable Output<String> certificateId) {
            $.certificateId = certificateId;
            return this;
        }

        /**
         * @param certificateId ID of the certificate to be provisioned to the given `keystore_id`.
         * 
         * @return builder
         * 
         */
        public Builder certificateId(String certificateId) {
            return certificateId(Output.of(certificateId));
        }

        /**
         * @param cloudCertificateId The ID of the provisioned certificate within the Cloud Keystore
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateId(@Nullable Output<String> cloudCertificateId) {
            $.cloudCertificateId = cloudCertificateId;
            return this;
        }

        /**
         * @param cloudCertificateId The ID of the provisioned certificate within the Cloud Keystore
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateId(String cloudCertificateId) {
            return cloudCertificateId(Output.of(cloudCertificateId));
        }

        /**
         * @param cloudCertificateMetadata Metadata of the provisioned certificate from the Cloud Keystore
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateMetadata(@Nullable Output<Map<String,String>> cloudCertificateMetadata) {
            $.cloudCertificateMetadata = cloudCertificateMetadata;
            return this;
        }

        /**
         * @param cloudCertificateMetadata Metadata of the provisioned certificate from the Cloud Keystore
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateMetadata(Map<String,String> cloudCertificateMetadata) {
            return cloudCertificateMetadata(Output.of(cloudCertificateMetadata));
        }

        /**
         * @param cloudCertificateName Name for the provisioned certificate in the keystore. If the name already exists, the provisioning will replace the previous certificate with the one from `certificate_id`. Only valid for AKV and GCM keystores.
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateName(@Nullable Output<String> cloudCertificateName) {
            $.cloudCertificateName = cloudCertificateName;
            return this;
        }

        /**
         * @param cloudCertificateName Name for the provisioned certificate in the keystore. If the name already exists, the provisioning will replace the previous certificate with the one from `certificate_id`. Only valid for AKV and GCM keystores.
         * 
         * @return builder
         * 
         */
        public Builder cloudCertificateName(String cloudCertificateName) {
            return cloudCertificateName(Output.of(cloudCertificateName));
        }

        /**
         * @param cloudKeystoreId ID of the cloud keystore where the certificate will be provisioned.
         * 
         * @return builder
         * 
         */
        public Builder cloudKeystoreId(@Nullable Output<String> cloudKeystoreId) {
            $.cloudKeystoreId = cloudKeystoreId;
            return this;
        }

        /**
         * @param cloudKeystoreId ID of the cloud keystore where the certificate will be provisioned.
         * 
         * @return builder
         * 
         */
        public Builder cloudKeystoreId(String cloudKeystoreId) {
            return cloudKeystoreId(Output.of(cloudKeystoreId));
        }

        /**
         * @param gcmCertScope The GCM certificate scope of the certificate. Only valid for GCM keystores. Supported values from GCM API documentation: DEFAULT, EDGE_CACHE, ALL_REGIONS.
         * 
         * @return builder
         * 
         */
        public Builder gcmCertScope(@Nullable Output<String> gcmCertScope) {
            $.gcmCertScope = gcmCertScope;
            return this;
        }

        /**
         * @param gcmCertScope The GCM certificate scope of the certificate. Only valid for GCM keystores. Supported values from GCM API documentation: DEFAULT, EDGE_CACHE, ALL_REGIONS.
         * 
         * @return builder
         * 
         */
        public Builder gcmCertScope(String gcmCertScope) {
            return gcmCertScope(Output.of(gcmCertScope));
        }

        public CloudKeystoreInstallationState build() {
            return $;
        }
    }

}
