// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCloudKeystorePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudKeystorePlainArgs Empty = new GetCloudKeystorePlainArgs();

    /**
     * ID of the cloud provider whom the cloud keystore to look up belongs to.
     * 
     */
    @Import(name="cloudProviderId", required=true)
    private String cloudProviderId;

    /**
     * @return ID of the cloud provider whom the cloud keystore to look up belongs to.
     * 
     */
    public String cloudProviderId() {
        return this.cloudProviderId;
    }

    /**
     * Name of the cloud keystore to look up.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return Name of the cloud keystore to look up.
     * 
     */
    public String name() {
        return this.name;
    }

    private GetCloudKeystorePlainArgs() {}

    private GetCloudKeystorePlainArgs(GetCloudKeystorePlainArgs $) {
        this.cloudProviderId = $.cloudProviderId;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudKeystorePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudKeystorePlainArgs $;

        public Builder() {
            $ = new GetCloudKeystorePlainArgs();
        }

        public Builder(GetCloudKeystorePlainArgs defaults) {
            $ = new GetCloudKeystorePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cloudProviderId ID of the cloud provider whom the cloud keystore to look up belongs to.
         * 
         * @return builder
         * 
         */
        public Builder cloudProviderId(String cloudProviderId) {
            $.cloudProviderId = cloudProviderId;
            return this;
        }

        /**
         * @param name Name of the cloud keystore to look up.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetCloudKeystorePlainArgs build() {
            if ($.cloudProviderId == null) {
                throw new MissingRequiredPropertyException("GetCloudKeystorePlainArgs", "cloudProviderId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetCloudKeystorePlainArgs", "name");
            }
            return $;
        }
    }

}
