// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCloudProviderArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudProviderArgs Empty = new GetCloudProviderArgs();

    /**
     * Name of the Cloud Provider to look up.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the Cloud Provider to look up.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private GetCloudProviderArgs() {}

    private GetCloudProviderArgs(GetCloudProviderArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudProviderArgs $;

        public Builder() {
            $ = new GetCloudProviderArgs();
        }

        public Builder(GetCloudProviderArgs defaults) {
            $ = new GetCloudProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name of the Cloud Provider to look up.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the Cloud Provider to look up.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetCloudProviderArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetCloudProviderArgs", "name");
            }
            return $;
        }
    }

}
