// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.venafi.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PolicyState extends com.pulumi.resources.ResourceArgs {

    public static final PolicyState Empty = new PolicyState();

    /**
     * policy specification
     * 
     */
    @Import(name="policySpecification")
    private @Nullable Output<String> policySpecification;

    /**
     * @return policy specification
     * 
     */
    public Optional<Output<String>> policySpecification() {
        return Optional.ofNullable(this.policySpecification);
    }

    /**
     * zone name
     * 
     */
    @Import(name="zone")
    private @Nullable Output<String> zone;

    /**
     * @return zone name
     * 
     */
    public Optional<Output<String>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private PolicyState() {}

    private PolicyState(PolicyState $) {
        this.policySpecification = $.policySpecification;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PolicyState $;

        public Builder() {
            $ = new PolicyState();
        }

        public Builder(PolicyState defaults) {
            $ = new PolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param policySpecification policy specification
         * 
         * @return builder
         * 
         */
        public Builder policySpecification(@Nullable Output<String> policySpecification) {
            $.policySpecification = policySpecification;
            return this;
        }

        /**
         * @param policySpecification policy specification
         * 
         * @return builder
         * 
         */
        public Builder policySpecification(String policySpecification) {
            return policySpecification(Output.of(policySpecification));
        }

        /**
         * @param zone zone name
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone zone name
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public PolicyState build() {
            return $;
        }
    }

}
