// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./certificate";
export * from "./policy";
export * from "./provider";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { Certificate } from "./certificate";
import { Policy } from "./policy";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "venafi:index/certificate:Certificate":
                return new Certificate(name, <any>undefined, { urn })
            case "venafi:index/policy:Policy":
                return new Policy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("venafi", "index/certificate", _module)
pulumi.runtime.registerResourceModule("venafi", "index/policy", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("venafi", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:venafi") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
